---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - daemonsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ubuntu.machinery.io.canonical.com
  resources:
  - ubuntukernelmodules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ubuntu.machinery.io.canonical.com
  resources:
  - ubuntukernelmodules/finalizers
  verbs:
  - create
  - delete
  - patch
  - update
- apiGroups:
  - ubuntu.machinery.io.canonical.com
  resources:
  - ubuntukernelmodules/status
  verbs:
  - create
  - delete
  - get
  - patch
  - update
