# permissions for end users to view ubuntukernelmodules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ubuntukernelmodule-viewer-role
rules:
- apiGroups:
  - ubuntu.machinery.io.canonical.com
  resources:
  - ubuntukernelmodules
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ubuntu.machinery.io.canonical.com
  resources:
  - ubuntukernelmodules/status
  verbs:
  - get
