# permissions for end users to view ubuntumachines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: UbuntuMachine-viewer-role
rules:
- apiGroups:
  - ubuntu.machinery.io.canonical.com
  resources:
  - ubuntumachines
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ubuntu.machinery.io.canonical.com
  resources:
  - ubuntumachines/status
  verbs:
  - get
