# permissions for end users to edit ubuntumachines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: UbuntuMachine-editor-role
rules:
- apiGroups:
  - ubuntu.machinery.io.canonical.com
  resources:
  - ubuntumachines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ubuntu.machinery.io.canonical.com
  resources:
  - ubuntumachines/status
  verbs:
  - get
