apiVersion: ubuntu.machinery.io.canonical.com/v1alpha1
kind: UbuntuMachineConfiguration
metadata:
  name: ubuntumachineconfiguration-sample
spec:
  desiredModules:
  - name: "nvme_core"
    flags: ""
  - name: "rfcomm"
    flags: ""
  desiredPackages:
    apt:
    - name: "build-essentials"
    snap:
    - name: "microk8s"
      confinement: "classic"