apiVersion: ubuntu.machinery.io.canonical.com/v1alpha1
kind: UbuntuMachine
metadata:
  name: ubuntumachine-sample
spec:
  desiredModules:
  - name: "nvme_core"
    flags: ""
  - name: "rfcomm"
    flags: ""
